### PR TITLE
Add an env var to disable the deprecation message

### LINKED ISSUE #8: Document how to silence deprecation messages
cut and paste this to create an example.

```bash
symfony new smoke-demo --webapp && cd smoke-demo
bin/console make:controller App
composer require --dev pierstoval/smoke-testing
cat <<'EOF' > tests/AllRoutesTest.php
<?php
namespace App\Tests;
use Pierstoval\SmokeTesting\SmokeTestStaticRoutes;
class AllRoutesTest extends SmokeTestStaticRoutes
{
    // That's all!
}
EOF

vendor/bin/phpunit 
```

I'm trying to hide that ugly deprecation message.

```bash
SYMFONY_DEPRECATIONS_HELPER='disabled=1' vendor/bin/phpunit
```

helps a bit, but it's still cluttered.

cool bundle, thanks for releasing it!

### PR DESCRIPTION
**Pull request by Pierstoval**
Fixes #8

### CODE REVIEW

**Comment by Pierstoval** [comment]
Friendly ping @tacman: by adding this env var to your global PHPUnit config, or your `.env.test` file, you can remove  the messages!

**Comment by tacman** [comment]
Can you provide an example?  This didn't work:

```xml
    <php>
        <ini name="display_errors" value="1" />
        <ini name="error_reporting" value="-1" />
        <env name="SMOKE_TESTING_ROUTES_METHODS" value="false" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
        <server name="SYMFONY_PHPUNIT_REMOVE" value="" />
        <server name="SYMFONY_PHPUNIT_VERSION" value="9.5" />
    </php>
```

**Comment by Pierstoval** [comment]
@tacman I've just published v1.1.0 with a small refactoring of the variable.

Could you update your project and test it?
Theoretically, just `<server name="SMOKE_TESTING_ROUTES_METHODS" value="off" />` should do the trick (I tested it on a big project of mine and it worked, but I'm curious about yours 👍)

(sorry for the long delay, I had tons of things preventing me from focusing properly)

**Comment by tacman** [comment]
Yep, works great!

I am still getting this deprecation, though:

  2x: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated
    2x in AllRoutesTest::testRoutesDoNotReturnInternalError from App\Tests

**Comment by Pierstoval** [comment]
The package isn't using `parse_str()` anywhere, this must come from your code calling this function with `null` as argument instead of a string

**Pull request merged**
